---

- name: configs > Templates
  template:
    src:  "{{ item.template|default(manala_logrotate_configs_template|ternary(manala_logrotate_configs_template, 'configs/empty.j2')) }}"
    dest: "{{ manala_logrotate_configs_dir }}/{{ item.file }}"
  with_items: "{{ manala_logrotate_configs }}"
